name: easehub_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  animations: ^2.0.11
  o3d: ^3.1.0
  provider: ^6.1.2
  firebase_core: ^2.27.0
  url_launcher: ^6.2.6
  flutter_phone_direct_caller: ^2.1.1
  flutter_charts: ^0.5.2
  charts_flutter: ^0.12.0
  flutter_chart: ^0.1.6
  firebase_messaging: ^14.7.19
  twilio_flutter: ^0.3.0
  fluttertoast: ^8.2.5
  flutter_calendar_carousel: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.71.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/applogo.svg"
  adaptive_icon_background: "#ffffff"  # Optional, only for Android
  adaptive_icon_foreground: "assets/applogo.svg"  # Optional, only for Android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/back.svg
    - assets/applogo.svg