// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ6mwUy24mJ5VjAzmZXebCBPZ0to2AhH0',
    appId: '1:917664454562:web:5fde8b1bdf80756cbf44fb',
    messagingSenderId: '917664454562',
    projectId: 'easehubapp-87569',
    authDomain: 'easehubapp-87569.firebaseapp.com',
    storageBucket: 'easehubapp-87569.appspot.com',
    measurementId: 'G-GJ1HGKJJQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1xeWDBcirMYzfxBhu1_KLMFUSYVcxTQ',
    appId: '1:917664454562:android:81f539c49807bf2dbf44fb',
    messagingSenderId: '917664454562',
    projectId: 'easehubapp-87569',
    storageBucket: 'easehubapp-87569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1JrB0x0bEiV2uKaHAQFT5VKDAtrRqaJs',
    appId: '1:917664454562:ios:e5fe98b7f90f4c49bf44fb',
    messagingSenderId: '917664454562',
    projectId: 'easehubapp-87569',
    storageBucket: 'easehubapp-87569.appspot.com',
    iosBundleId: 'com.example.easehubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1JrB0x0bEiV2uKaHAQFT5VKDAtrRqaJs',
    appId: '1:917664454562:ios:e5fe98b7f90f4c49bf44fb',
    messagingSenderId: '917664454562',
    projectId: 'easehubapp-87569',
    storageBucket: 'easehubapp-87569.appspot.com',
    iosBundleId: 'com.example.easehubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ6mwUy24mJ5VjAzmZXebCBPZ0to2AhH0',
    appId: '1:917664454562:web:c38cfafdeac30bcbbf44fb',
    messagingSenderId: '917664454562',
    projectId: 'easehubapp-87569',
    authDomain: 'easehubapp-87569.firebaseapp.com',
    storageBucket: 'easehubapp-87569.appspot.com',
    measurementId: 'G-LKF81SYXJ9',
  );
}
